import { type NextPage } from 'next';
import Head from 'next/head';
import { api } from '~/utils/api';

import { SignIn, SignInButton, useUser } from '@clerk/nextjs';
import CreatePostWizard from '~/components/CreatePostWizard';
import { Feed } from '~/components/Feed';

const LandingPage: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // Start fetching asap - cached data
  api.posts.getAll.useQuery();

  // Return empty div, if user isn't loaded
  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Scrabble Away LV</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl ">
          <div className="flex border-b border-slate-400 p-4">
            {!isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {isSignedIn && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default LandingPage;
